# 📊 Data Selection & Sorting with Pandas

## 📌 Objective
The objective of this notebook is to explore different techniques for selecting and accessing data using Pandas, including column selection, row selection, and conditional filtering.

In [3]:
import pandas as pd
df = pd.read_csv("Bank_churn.csv")

### 📊 Data Types Overview
- Displays the data type of each column  
- Useful for understanding which columns are numerical or categorical before selection

In [4]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

### 📊 Column Selection
- Selecting a single column returns a Series  
- Selecting multiple columns returns a DataFrame  
- Helps isolate relevant features for analysis

In [5]:
# Single column: to obtain series we use single []
df["Surname"]

0        Hargrave
1            Hill
2            Onio
3            Boni
4        Mitchell
          ...
9995     Obijiaku
9996    Johnstone
9997          Liu
9998    Sabbatini
9999       Walker
Name: Surname, Length: 10000, dtype: object

In [6]:
# Multiple columns: to obtain series we use double[[]]
df[["Surname", "CreditScore"]]

        Surname  CreditScore
0      Hargrave          619
1          Hill          608
2          Onio          502
3          Boni          699
4      Mitchell          850
...         ...          ...
9995   Obijiaku          771
9996  Johnstone          516
9997        Liu          709
9998  Sabbatini          772
9999     Walker          792

[10000 rows x 2 columns]

In [7]:
df[["Surname", "CreditScore", "Geography"]]

        Surname  CreditScore Geography
0      Hargrave          619    France
1          Hill          608     Spain
2          Onio          502    France
3          Boni          699    France
4      Mitchell          850     Spain
...         ...          ...       ...
9995   Obijiaku          771    France
9996  Johnstone          516    France
9997        Liu          709    France
9998  Sabbatini          772   Germany
9999     Walker          792    France

[10000 rows x 3 columns]

### 🔄 Data Sorting

- Sorting is used to organize data based on one or more columns  
- Helps identify top or bottom records and understand data distribution  

**Types of Sorting:**
- Sorting by a single column  
- Sorting by multiple columns  
- Custom sorting order using ascending/descending values  

**Key Points:**
- By default, sorting is in ascending order  
- `ascending=False` is used for descending order  
- Multiple columns can be sorted with different sort orders  

Sorting improves data readability and prepares it for deeper analysis.

In [8]:
# Sort by single column
df.sort_values("Age")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
2021,2022,15795519,Vasiliev,716,Germany,Female,18,3,128743.80,1,0,0,197322.13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,3388,15798024,Lori,537,Germany,Male,84,8,92242.34,1,1,1,186235.98,0
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0

In [9]:
# Sort multiple columns
df.sort_values(["Age", "CreditScore"])

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9782,9783,15728829,Weigel,509,France,Male,18,7,102983.91,1,1,0,171770.58,0
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
9029,9030,15722701,Bruno,594,Germany,Male,18,1,132694.73,1,1,0,167689.56,0
7334,7335,15759133,Vaguine,616,France,Male,18,6,0.00,2,1,1,27308.58,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,3388,15798024,Lori,537,Germany,Male,84,8,92242.34,1,1,1,186235.98,0
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0

In [10]:
# Custom sorting order
df.sort_values(["Age", "CreditScore", "Tenure"],ascending=[False, True, True])

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3330,3331,15657439,Chao,738,France,Male,18,4,0.00,2,1,1,47799.15,0
3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
9501,9502,15634146,Hou,835,Germany,Male,18,2,142872.36,1,1,1,117632.63,0
746,747,15787619,Hsieh,844,France,Male,18,2,160980.03,1,0,0,145936.28,0

## 💡 Observations

- Column selection helps isolate relevant features for focused analysis  
- The dataset contains both categorical and numerical variables  
- Sorting allows identification of top or bottom records based on specific criteria  
- Multi-column sorting enables deeper insights by applying hierarchical ordering  
- Combining selection and sorting improves data readability and analysis efficiency

## 📌 Conclusion

- Learned how to select relevant columns from a dataset  
- Applied sorting techniques to organize data effectively  
- Understood how sorting enhances data interpretation  
- Established a stronger foundation for further data analysis